import { autoGeneratedFile } from "@recursica/common";
import type { RecursicaConfiguration } from "@recursica/schemas";

export function createRecursicaObject(
  project: RecursicaConfiguration["project"],
  outputPath: string,
) {
  const projectName =
    typeof project === "string" ? project : (project.name ?? "Recursica");
  const tokens = `Recursica${projectName}Tokens`;
  const contract = `Recursica${projectName}ContractTheme`;
  const uiKit = `Recursica${projectName}UiKit`;

  const recursicaObjectContent = `${autoGeneratedFile()}
import { ${tokens} } from './${tokens}';
import { themeVars } from './${contract}.css';
import { uiKit } from './${uiKit}';

export const recursica = {
  ...uiKit,
  ...themeVars,
  ...${tokens},
}
`;
  return {
    content: recursicaObjectContent,
    path: outputPath + "/Recursica.ts",
    filename: "Recursica.ts",
  };
}
