import { autoGeneratedFile } from "../utils/autoGeneratedFile";
import fs from "fs";
import path from "path";
import { ExportingResult } from "../types";

export function generateBorderRadiusType(
  borderRadius: string[],
  outputPath: string,
): ExportingResult {
  const borderRadiusTypeContent = `${autoGeneratedFile()}
export type RecursicaBorderRadiusType = ${borderRadius
    .map((key) => `'${key}'`)
    .join(" | ")};
`;

  const filename = path.join(outputPath, "RecursicaBorderRadiusType.ts");
  fs.writeFileSync(filename, borderRadiusTypeContent);
  return {
    content: borderRadiusTypeContent,
    path: `${outputPath}/RecursicaBorderRadiusType.ts`,
    filename: "RecursicaBorderRadiusType.ts",
  };
}
