import { autoGeneratedFile } from "@recursica/common";
import { ExportingResult } from "../types";

export function generateSpacersType(
  spacerTokens: string[],
  outputPath: string,
): ExportingResult {
  const spacersType = `${autoGeneratedFile()}
export type RecursicaSpacersType = \n\t"${spacerTokens.join('" |\n\t"')}";\n`;

  return {
    content: spacersType,
    path: `${outputPath}/RecursicaSpacersType.ts`,
    filename: "RecursicaSpacersType.ts",
  };
}
