import fs from "fs";
import path from "path";
import { autoGeneratedFile } from "../utils/autoGeneratedFile";
import { ExportingResult } from "../types";

export function generateSpacersType(
  spacerTokens: string[],
  outputPath: string,
): ExportingResult {
  const spacersType = `${autoGeneratedFile()}
export type RecursicaSpacersType = \n\t"${spacerTokens.join('" |\n\t"')}";\n`;
  fs.writeFileSync(
    path.join(outputPath, "RecursicaSpacersType.ts"),
    spacersType,
  );

  return {
    content: spacersType,
    path: `${outputPath}/RecursicaSpacersType.ts`,
    filename: "RecursicaSpacersType.ts",
  };
}
